version: '3.8'
services:
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: url-shortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/bitnami/postgresql
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://docker:docker@db:5432/url-shortener
      - JWT_SECRET=3e914f5ed025e175bd236f9a027939ad26d824ad7bb86fc466e2a205db79a424
      - SERVER_ADDRESS=https://localhost:3000
    command: sh -c "npx prisma migrate dev && npm run start:dev"
volumes:
  db_data: